# Generated by Django 4.1.7 on 2023-03-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0003_alter_instructor_options_alter_period_options_and_more'),
        ('courseinfo', '0003_auto_20210213_0126'),
    ]

    operations = [
    ]
